# -- Markup --
# These settings are required for the theme to function.

[goldmark]
[goldmark.renderer]
unsafe = true

[highlight]
noClasses = false

# Disable table of contents generation for now, the colors in dark mode are off.
[tableOfContents]
startLevel = 0
endLevel = 0
