[[imports]]
path = "github.com/jpanther/congo/v2"

[hugoVersion]
extended = true
min = "0.87.0"

[privacy]
[privacy.disqus]
disable = true
[privacy.googleAnalytics]
disable = true
[privacy.instagram]
disable = true
[privacy.twitter]
disable = true
[privacy.vimeo]
disable = true
[privacy.youtube]
disable = true
